scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 2s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']       
  - job_name: 'health-checks'
    scrape_interval: 60s
    static_configs:
      - targets: ['host.docker.internal:5085']
    metrics_path: "/healthmetrics"